apiVersion: apps/v1
kind: Deployment
metadata:
  name: baiduspider-deploy
  labels:
    app: baiduspider-app
spec:
  selector:
    matchLabels:
      app: baiduspider-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: baiduspider-app
    spec:
      containers:
        - name: baiduspider-app
          image: samzhangjy/baiduspider:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
